Added changes to override the `commandTimeout` caps to resolve issues with default time out of `5s`
projectxyzio/appium-altunity-plugin pull request #9
Opened 2023-07-18 12:39 UTC by bipin-k

[*] Added changes to override the `commandTimeout` caps to resolve issues with default time out of `5s`

2023-07-18 12:40 UTC, bipin-k commented
@jlipps This change couldn't be tested locally as the below issue is yet to be resolved.
https://github.com/headspinio/appium-altunity-plugin/issues/8

2023-07-19 23:20 UTC, jlipps requested changes
change itself looks good, couple small things to fix

2023-07-19 23:20 UTC, jlipps commented on package.json
> -  "version": "1.3.2",
in a PR you shouldn't do things like update the version, that is for the maintainer to do when something is published

2023-07-19 23:20 UTC, jlipps commented on src/client/index.ts
> +            commandTimeout : opts.commandTimeout
please follow the code style for spacing

2023-07-20 20:14 UTC, jlipps approved these changes

2023-07-20 20:15 UTC, merged